project:
  type: website
  output-dir: docs

website:
  title: "Tim Chen"
  site-url: "https://weitingchen.com"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: courses.qmd
        text: Courses
      - href: coffee.qmd
        text: Coffee
      - text: Projects
        menu: 
          - toronto-crime-analysis.qmd
          - us-presidential election.qmd
          - toronto-shelter-analysis.qmd
          - bike-theft-analysis.qmd
          - iMDb-analysis.qmd
          - mayohr-intern.qmd
          - traffic-collision-analysis.qmd
      - href: https://timsplayland.vercel.app/
        text: Portfolio
      - text: "Resume"
        href: pdfs/resume.pdf
      - icon: github
        href: https://github.com/timchen0326
      - icon: envelope
        href: "mailto:timchen0326ca@gmail.com"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true

